login_text_zh = {
    "username_text": "用户名",
    "username_placeholder": "请输入用户名",
    "username_help": "注册时使用的用户名",
    "username_help_huozi": "支持活字登录",
    "password_text": "密码",
    "password_placeholder": "请输入密码",
    "password_help": "注册时使用的密码",
    "password_help_huozi": "支持活字登录",
    "login_button_name": "登录",
    "login_button_help": "点击登录",
    "login_success": "登录成功",
    "login_success_huozi": "活字登录成功",
    "login_fail": "登录失败",

    "name_signup_text": "姓名 *",
    "name_signup_placeholder": "请输入姓名",
    "name_signup_help": "你的姓名",
    "email_signup_text": "邮件地址 *",
    "email_signup_placeholder": "请输入邮件地址",
    "email_signup_help": "用于密码找回",
    "username_signup_text": "用户名 *",
    "username_signup_placeholder": "请输入用户名",
    "username_signup_help": "用于登录，这是你的唯一标识",
    "password_signup_text": "密码 *",
    "password_signup_placeholder": "设置你的密码",
    "password_signup_help": "你的密码",
    "signup_button_name": "注册",
    "signup_button_help": "点击注册",
    "signup_name_error": "请输入有效的姓名！",
    "signup_email_error": "请输入有效的邮件地址！",
    "signup_email_error_unique": "邮箱 {email_sign_up} 已被注册！请尝试其他邮箱。",
    "signup_username_error": "用户名 {username_sign_up} 已被注册！请尝试其他用户名。",
    "signup_username_none": "请输入用户名！",
    "signup_success_text": "注册成功！",

    "forgotpwd_email_text": "邮件地址",
    "forgotpwd_email_placeholder": "请输入注册时使用的邮件地址",
    "forgotpwd_email_help": "用于接收密码",
    "forgotpwd_button_text": "获取密码",
    "forgotpwd_button_help": "点击获取随机密码，发送至您的邮箱",
    "forgotpwd_email_error_exist": "该邮件地址未注册！",
    "forgotpwd_success_text": "密码已发送至您的邮箱！",

    "resetpwd_email_text": "邮件地址",
    "resetpwd_email_placeholder": "请输入你的邮件地址",
    "resetpwd_email_help": "注册时使用的邮件地址",
    "resetpwd_currentpwd_text": "旧密码",
    "resetpwd_currentpwd_placeholder": "请输入你的旧密码",
    "resetpwd_currentpwd_help": "之前的密码或者通过邮件发送的临时密码",
    "resetpwd_newpwd_text": "新密码",
    "resetpwd_newpwd_placeholder": "请输入新密码",
    "resetpwd_newpwd_help": "设置你的新密码",
    "resetpwd_newpwd1_text": "确认新密码",
    "resetpwd_newpwd1_placeholder": "请再次输入新密码",
    "resetpwd_newpwd1_help": "确认新密码",
    "resetpwd_button_text": "重置密码",
    "resetpwd_button_help": "点击重置密码",
    "resetpwd_email_error_exist": "该邮件地址未注册！",
    "resetpwd_currentpwd_error": "旧密码错误！",
    "resetpwd_newpwd_error": "两次输入的新密码不匹配！",
    "resetpwd_success_text": "密码重置成功！",

    "logout_button_text": "登出",
    "logout_button_help": "点击登出",

    "tab_login": "🔑 登录",
    "tab_login_huozi": "🛂 使用活字登录",
    "tab_signup": "📝 注册账号",
    "tab_forgotpwd": "❓ 忘记密码",
    "tab_resetpwd": "🔄 重设密码",

    "login_title": "# 珠算-SQL",
}

login_text_en = {
    "username_text": "Username",
    "username_placeholder": "Enter your username",
    "username_help": "The username you used during registration",
    "username_help_huozi": "Supports Huozi login",
    "password_text": "Password",
    "password_placeholder": "Enter your password",
    "password_help": "The password you used during registration",
    "password_help_huozi": "Supports Huozi login",
    "login_button_name": "Login",
    "login_button_help": "Click to log in",
    "login_success": "Login successful",
    "login_success_huozi": "Huozi login successful",
    "login_fail": "Login failed",

    "name_signup_text": "Full Name *",
    "name_signup_placeholder": "Enter your full name",
    "name_signup_help": "Your full name",
    "email_signup_text": "Email Address *",
    "email_signup_placeholder": "Enter your email address",
    "email_signup_help": "Used for password recovery",
    "username_signup_text": "Username *",
    "username_signup_placeholder": "Enter your username",
    "username_signup_help": "Used for login, this is your unique identifier",
    "password_signup_text": "Password *",
    "password_signup_placeholder": "Set your password",
    "password_signup_help": "Your password",
    "signup_button_name": "Sign Up",
    "signup_button_help": "Click to register",
    "signup_name_error": "Please enter a valid name!",
    "signup_email_error": "Please enter a valid email address!",
    "signup_email_error_unique": "Email {email_sign_up} is already taken! Please try another email.",
    "signup_username_error": "Username {username_sign_up} is already taken! Please try another username.",
    "signup_username_none": "Please enter a username!",
    "signup_success_text": "Registration successful!",

    "forgotpwd_email_text": "Email Address",
    "forgotpwd_email_placeholder": "Enter the email address used during registration",
    "forgotpwd_email_help": "Used to receive your password",
    "forgotpwd_button_text": "Get Password",
    "forgotpwd_button_help": "Click to get a random password sent to your email",
    "forgotpwd_email_error_exist": "This email address is not registered!",
    "forgotpwd_success_text": "Password has been sent to your email!",

    "resetpwd_email_text": "Email Address",
    "resetpwd_email_placeholder": "Enter your email address",
    "resetpwd_email_help": "The email address used during registration",
    "resetpwd_currentpwd_text": "Old Password",
    "resetpwd_currentpwd_placeholder": "Enter your old password",
    "resetpwd_currentpwd_help": "The previous password or the temporary password sent via email",
    "resetpwd_newpwd_text": "New Password",
    "resetpwd_newpwd_placeholder": "Enter your new password",
    "resetpwd_newpwd_help": "Set your new password",
    "resetpwd_newpwd1_text": "Confirm New Password",
    "resetpwd_newpwd1_placeholder": "Enter your new password again",
    "resetpwd_newpwd1_help": "Confirm your new password",
    "resetpwd_button_text": "Reset Password",
    "resetpwd_button_help": "Click to reset password",
    "resetpwd_email_error_exist": "This email address is not registered!",
    "resetpwd_currentpwd_error": "Old password is incorrect!",
    "resetpwd_newpwd_error": "The new passwords do not match!",
    "resetpwd_success_text": "Password reset successful!",

    "logout_button_text": "Logout",
    "logout_button_help": "Click to log out",

    "tab_login": "🔑 Login",
    "tab_login_huozi": "🛂 Use Huozi login",
    "tab_signup": "📝 Sign up",
    "tab_forgotpwd": "❓ Forgot password",
    "tab_resetpwd": "🔄 Reset password",

    "login_title": "# Abacus-SQL",
}

chat_text_zh = {
    "icon_text": "聊天窗口",
    "current_chat_label": "历史聊天窗口",
    "create_button_text": "新建",
    "delete_button_text": "删除",
    "set_name_text": "设定窗口名称",
    "set_name_placeholder": "点击输入",
    "set_name_caption": "- 进行会话的重命名时不要使用下划线",
    "model_text": "选择使用的模型",
    "model_display_options": ["Qwen2.5-Coder 7b", "GPT-4o", "DeepSeek-R1"],
    "model_actual_values": ["Qwen2.5-Coder_7b", "GPT-4o", "deepseek-reasoner"],
    "model_default_url": ["", "https://api.openai.com/v1", "https://api.deepseek.com/v1"],
    "model_help": "选择用于生成SQL查询的模型，Qwen2.5-Coder 7b是我们在部署的模型，同时支持GPT-4o等模型，可以使用api_key调用。",
    "model_api_key_text": "API 密钥",
    "model_api_key_placeholder": "请输入API密钥",
    "model_api_base_text": "API BASE（可不填，默认为服务商提供的网址）",
    "model_api_base_placeholder": "请输入API BASE",
}

chat_text_en = {
    "icon_text": "Chat Window",
    "current_chat_label": "History Chat Window",
    "create_button_text": "New",
    "delete_button_text": "Delete",
    "set_name_text": "Set Window Name",
    "set_name_placeholder": "Click to enter",
    "set_name_caption": "- Do not use underscores when renaming the conversation",
    "model_text": "Select the model to use",
    "model_display_options": ["Qwen2.5-Coder 7b", "GPT-4o", "DeepSeek-R1"],
    "model_actual_values": ["Qwen2.5-Coder_7b", "GPT-4o", "deepseek-reasoner"],
    "model_default_url": ["", "https://api.openai.com/v1", "https://api.deepseek.com/v1"],
    "model_help": "Select the model used to generate SQL queries. Qwen2.5-Coder 7b is the model we have deployed, and other models such as GPT-4o are also supported, which can be called using an api_key.",
    "model_api_key_text": "API Key",
    "model_api_key_placeholder": "Enter API key",
    "model_api_base_text": "API BASE (optional, default is the URL provided by the service provider)",
    "model_api_base_placeholder": "Enter API BASE",
}

show_db_text_zh = {
    "db_example": "./data/example/example_db.zip",
    "select_table_text": "此数据库中的表",
    "select_table_content_text": "表 `{selected_table}`中的数据:",
    "select_table_no_table": "在这个数据库中没有找到任何表。",
    "uploaded_files_text": "已上传的数据库文件",
    "uploaded_files_checkbox": "选择 {file_name}",
    "uploaded_files_selected": "你选择了以下文件：{selected_files}",
    "uploaded_files_delete": "删除选中的文件",
    "show_db_text": "请选择一个数据库",
    "show_db_upload": "请选择一个SQLite文件或者zip文件",
    "show_db_upload_help": "zip文件应该包含一个或多个SQLite文件，请不要包含嵌套文件夹。",
    "show_db_download": "下载示例文件",
    "show_db_download_help": "点击下载示例文件",
    "show_db_upload_button": "上传",
    "show_db_select": "选择数据库文件",
    "show_db_no_file": "请上传一个SQLite文件。",
}

show_db_text_en = {
    "db_example": "./data/example/example_db_en.zip",
    "select_table_text": "Tables in this database",
    "select_table_content_text": "Data in table `{selected_table}`:",
    "select_table_no_table": "No tables found in this database.",
    "uploaded_files_text": "Uploaded database files",
    "uploaded_files_checkbox": "Select {file_name}",
    "uploaded_files_selected": "You have selected the following files: {selected_files}",
    "uploaded_files_delete": "Delete selected files",
    "show_db_text": "Please select a database",
    "show_db_upload": "Please select an SQLite file or a zip file",
    "show_db_upload_help": "The zip file should contain one or more SQLite files, please do not include nested folders.",
    "show_db_download": "Download sample file",
    "show_db_download_help": "Click to download the sample file",
    "show_db_upload_button": "Upload",
    "show_db_select": "Select database file",
    "show_db_no_file": "Please upload an SQLite file.",
}

config_text_zh = {
    "config_title": "# 用户设置",
    "config_resetpwd": "修改密码（活字用户请前往官网修改）",
    "user_slogan": "探索无限",
}

config_text_en = {
    "config_title": "# User Settings",
    "config_resetpwd": "Change Password (Huozi users, please visit the official website to change password)",
    "user_slogan": "Explore the Infinite",
}

strategy_text_zh = {
    "strategy_title": "# 方法",
    "strategy_demo": "在提示中使用示例",
    "strategy_encore": "使用合成后的示例集",
    "strategy_demo_num": "示例个数",
    "strategy_presql": "预生成sql",
    "strategy_self_debug": "自我纠错",
    "info_list" :[
        "- 在这里，你可以上传自己的数据集，我们将对其进行增广以初始化demonstration",
        "- 在生成sql语句时，我们将从增广后的数据集和我们预先准备好的示例集中选取示例以更好的生成sql语句",
        "- 如果不使用自己的数据集，我们将使用我们预先准备好的示例集",
    ],
    "format_list" :[
        "数据集应为一个zip文件，其中包含：",
        "一个json文件，其中包含一个列表（至少包含两个不同",
        "数据库的两个问题），每个列表应遵循以下格式：",
        "```json\n{\n'question': 一个问题,\n'query': 该问题对应的sql语句,\n'db_id': 该问题使用的数据库文件id，\n\t也就是对应文件的文件名前缀\n}\n```",
        "一个database文件夹，其中包含各个名为'db_id'的文件夹，",
        "每个文件夹中包含一个名为'db_id'.sqlite的数据库文件",
    ],
    "fused_text": "示例合成",
    "fused_upload": "选择一个zip文件",
    "fused_download": "下载示例文件",
    "fused_example_file": "./data/example/example_fused.zip",
    "fused_info": "显示详细信息",
    "fused_info_help": "显示关于示例合成的详细信息",
    "fused_button": "上传数据集",
    "fused_button_help": "上传你的数据集",
    "fused_success": "上传的数据集已经经过示例合成",
    "fused_spinner": "正在等待...",
}

strategy_text_en = {
    "strategy_title": "# Method",
    "strategy_demo": "Use examples in prompts",
    "strategy_encore": "Use augmented example set",
    "strategy_demo_num": "Number of examples",
    "strategy_presql": "Pre-generate SQL",
    "strategy_self_debug": "Self-correction",
    "info_list" :[
        "- Here, you can upload your own dataset, which we will augment to initialize the demonstration.",
        "- When generating SQL statements, we will select examples from the augmented dataset and our pre-prepared example set to better generate SQL queries.",
        "- If you do not use your own dataset, we will use our pre-prepared example set.",
    ],
    "format_list" :[
        "The dataset should be a zip file containing:",
        "A JSON file containing a list (at least two questions from different databases), each list should follow this format:",
        "```json\n{\n'question': The question,\n'query': The SQL query corresponding to the question,\n'db_id': The database file ID used for the question,\n\twhich is the prefix of the file name\n}\n```",
        "A 'database' folder containing subfolders named 'db_id',",
        "Each folder should contain a database file named 'db_id.sqlite'",
    ],
    "fused_text": "Example Fusion",
    "fused_upload": "Select a zip file",
    "fused_download": "Download sample file",
    "fused_example_file": "./data/example/example_fused.zip",
    "fused_info": "Show detailed information",
    "fused_info_help": "Show detailed information about example fusion",
    "fused_button": "Upload dataset",
    "fused_button_help": "Upload your dataset",
    "fused_success": "The uploaded dataset has been fused with examples",
    "fused_spinner": "Waiting...",
}

main_chat_text_zh = {
    "feedback_text": "在这里输入你的反馈",
    "feedback_button": "提交反馈",
    "feedback_button_success": "反馈已提交！",
    "header_text": "# 和 珠算-SQL 进行对话 💬🦉",
    "info_text": "注意：这是 珠算-SQL 演示页面，你可以上传数据库文件并提问，AI会尝试生成SQL查询。",
    "info_upload_text": "请上传一个SQLite文件或者zip文件",
}

main_chat_text_en = {
    "feedback_text": "Enter your feedback here",
    "feedback_button": "Submit Feedback",
    "feedback_button_success": "Feedback submitted!",
    "header_text": "# Chat with Abacus-SQL 💬🦉",
    "info_text": "Note: This is the Abacus-SQL demo page. You can upload a database file and ask questions, and the AI will attempt to generate SQL queries.",
    "info_upload_text": "Please upload an SQLite file or a zip file",
}

history_text_zh = {
    "status_text": "正在处理用户输入……",
    "status_debug_success": "sql语句正确",
    "status_debug_fail": "sql语句错误，重新生成",
    "status_debug_fail_yield": "\n\n**第{flag_i}次纠错：**\n\n",
    "status_entity_debug": "正在进行实体纠错……",
    "status_entity_debug_yield": "\n\n**实体纠错**\n\n",
    "status_skeleton_debug": "正在进行骨架纠错……",
    "status_skeleton_debug_yield": "\n\n**骨架纠错**\n\n",
    "status_execution_debug": "正在进行执行纠错……",
    "status_execution_debug_yield": "\n\n**执行纠错**\n\n",
    "request_error": "请求失败: 未连接到服务器，请稍后再试。",
    "other_error": "发生错误: {e}",

    "message_init": "你好，我是 AI 助手，主要用于生成 SQL 查询语句。有什么可以帮助你的吗？",
    "sql_excution": "执行SQL语句",
    "sql_excution_delete": "删除执行结果",
    "message_show_db": "数据库: {database}",
}

history_text_en = {
    "status_text": "Processing user input...",
    "status_debug_success": "SQL statement is correct",
    "status_debug_fail": "SQL statement is incorrect, regenerating",
    "status_debug_fail_yield": "\n\n**Correction attempt {flag_i}:**\n\n",
    "status_entity_debug": "Performing entity correction...",
    "status_entity_debug_yield": "\n\n**Entity Correction**\n\n",
    "status_skeleton_debug": "Performing skeleton correction...",
    "status_skeleton_debug_yield": "\n\n**Skeleton Correction**\n\n",
    "status_execution_debug": "Performing execution correction...",
    "status_execution_debug_yield": "\n\n**Execution Correction**\n\n",
    "request_error": "Request failed: Not connected to the server. Please try again later.",
    "other_error": "An error occurred: {str(e)}",

    "message_init": "Hello, I am an AI assistant primarily designed to generate SQL queries. How can I assist you today?",
    "sql_excution": "Execute SQL",
    "sql_excution_delete": "Delete results",
    "message_show_db": "Database: {database}",
}

app_text_zh = {
    "chat": "💬 对话",
    "database": "🗄️ 数据库",
    "config": "⚙️ 设置",
    "strategy": "📑 方法",
    "lang_choose": "# 选择语言",
    "init_msg": "你好，我是 AI 助手，主要用于生成 SQL 查询语句。有什么可以帮助你的吗？",
}

app_text_en = {
    "chat": "💬 Chat",
    "database": "🗄️ Database",
    "config": "⚙️ Settings",
    "strategy": "📑 Method",
    "lang_choose": "# Choose Language",
    "init_msg": "Hello, I am an AI assistant primarily designed to generate SQL queries. How can I assist you today?",
}

error_messages_ch = {
    'RateLimitError': '速率限制错误，稍后重试。',
    'AuthenticationError': '身份验证错误：身份验证失败，请检查 API 密钥是否正确。',
    'InvalidRequestError': '请求无效：请求格式或参数不正确，请检查请求参数。',
    'APIConnectionError': 'API 连接错误：无法连接到 OpenAI API，请检查网络连接。',
    'Timeout': '请求超时：请求处理时间过长，请稍后再试。',
    'InternalServerError': '服务器内部错误：OpenAI 服务器出现问题，请稍后再试。',
    'ServiceUnavailableError': '服务不可用：OpenAI 服务暂时不可用，请稍后再试。',
    'PermissionError': '权限错误：您没有执行此操作的权限，请检查权限设置。',
    'UnknownError': '发生未知错误：出现了无法预料的错误，请联系支持团队。'
}

error_messages_en = {
    'RateLimitError': 'Rate limit error, please retry later.',
    'AuthenticationError': 'Authentication error: Authentication failed, please check if the API key is correct.',
    'InvalidRequestError': 'Invalid request: The request format or parameters are incorrect, please check the request parameters.',
    'APIConnectionError': 'API connection error: Unable to connect to OpenAI API, please check your network connection.',
    'Timeout': 'Request timeout: The request took too long to process, please try again later.',
    'InternalServerError': 'Internal server error: There is an issue with the OpenAI server, please try again later.',
    'ServiceUnavailableError': 'Service unavailable: The OpenAI service is temporarily unavailable, please try again later.',
    'PermissionError': 'Permission error: You do not have permission to perform this action, please check your permissions.',
    'UnknownError': 'Unknown error: An unexpected error occurred, please contact support.'
}

text = {
    "zh": {
        "login": login_text_zh,
        "chat": chat_text_zh,
        "show_db": show_db_text_zh,
        "config": config_text_zh,
        "strategy": strategy_text_zh,
        "main_chat": main_chat_text_zh,
        "history": history_text_zh,
        "app": app_text_zh,
        "error": error_messages_ch,
    },
    "en": {
        "login": login_text_en,
        "chat": chat_text_en,
        "show_db": show_db_text_en,
        "config": config_text_en,
        "strategy": strategy_text_en,
        "main_chat": main_chat_text_en,
        "history": history_text_en,
        "app": app_text_en,
        "error": error_messages_en,
    }
}
